### ISSUE TITLE
Half the parts too big to print on my printer

### ISSUE THREAD

**Issue by Draegon366** [nevermore3d/StealthMax#11]
In what way could I slice the large parts to be able to fit on a 220x220mm print bed?

**Comment by 0ndsk4** [comment]
Stealthmax is a large-scale filter made for larger machines. It will not fit on a 220 bed unfortunately. 

The new smaller size is made to fit 250x250, but it’s hard to make it much smaller than that. Regular version needs a 300mm bed even. Sorry :/
