### ISSUE TITLE
recommended print settings

### ISSUE THREAD

**Issue by slaesh** [nevermore3d/StealthMax#23]
hey there, great project - thanks!

I am planning to build a stealthmax s..
first (maybe not last.. ;D) question: **any recommended print settings?**

wall counts?
infill?
etc.. :)

**Comment by slaesh** [comment]
thanks for that quick response! =) will let this issue open, until I created a PR for adding this somewhere into the README.. ;)

**Comment by itay-grudev** [comment]
@slaesh There is a WIP [Wiki](https://github.com/nevermore3d/StealthMax/wiki/Print-Settings) page now.
