### ISSUE TITLE
Which parts to print?

### ISSUE THREAD

**Issue by fabikroeger** [nevermore3d/StealthMax#3]
Hello there,

i want to print the StealthMax but i am not sure which parts to print neither if the offered parts in the .3mf are complete . 
A list of parts which needed to be printed would be awesome.

Greetings
Fabian

**Comment by 0ndsk4** [comment]
Hey! Thanks for the interest! Stealthmax is still being worked on, and as such there’s no official bom or build guide quite yet. I did post a few stls to make it easier to test print the large parts with success. 
If you’re interested in trying the early build please join Nevermore discord to see where stuff is at and share stealthmax experiences. Hoping to get this to a public beta stage within a few weeks. 

https://discord.gg/UbsMA7gb
