### ISSUE TITLE
STL's potentailly in incorrect place

### ISSUE THREAD

**Issue by Dark360** [nevermore3d/StealthMax#36]
I am currently printing my Stealthmax for my Voron and after chatting with someone on Discord who is printing the Direct option they noticied that they were missing the supports my Main Chamber.

When I said the supports were built in, they said they had to export the STEP files of the Main Chamber directly from the F3D as there were no STL's for the direct option. (I understand that the supports are in the F3D, but these are hidden by default.)

I think the issues lies with this statement:

_"Try these modded files. They replace the files with the same numbers from the regular STL directory."_

**2-Main_Chamber.stl** and **2-Main_Chamber_HEPA_Cover.stl** are not in the **STL** directory, but in **STL/Voron-Back-Panel-Cutout_Mount** directory

Can these STL's be moved into the **STL** directoy or copies added to the **STL/Direct-On-Panel_Mount** subdirectory?

**Comment by FatalBulletHit** [comment]
Should be fixed with #37 and #39 and will be improved for the StealthMax S soonTM as well.
